@host = http://localhost:5000
@email = test@example.com
@password = Password123!
@profileId = cf6d7512-ff82-456d-b350-b1b914410b25 
### Authentication

### Login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("token", response.body.data.token);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### Account

### Get User Info (to get ID for refresh)
GET {{host}}/account
Authorization: Bearer {{token}}

> {%
    client.global.set("userId", response.body.data.id);
    client.global.set("userName", response.body.data.username);
%}

### Create Account
POST {{host}}/account
Content-Type: application/json

{
  "username": "newuser",
  "email": "test@example.com",
  "password": "Password123!"
}

### Authentication (Refresh)

### Refresh Token
POST {{host}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}",
  "userId": "{{userId}}",
  "userName": "{{userName}}"
}

### Profile

### Get My Profile
GET {{host}}/profile
Authorization: Bearer {{token}}

> {%
    client.global.set("profileId", response.body.data.id);
%}
#### Deprecated : Unused
#### Create Profile
#POST {{host}}/profile
#Authorization: Bearer {{token}}
#Content-Type: application/json
#
#{
#  "userId": "{{userId}}",
#  "displayName": "My Display Name",
#  "avatarUrl": "https://example.com/avatar.png",
#  "birthDate": "2000-01-01T00:00:00",
#  "gender": 1,
#  "bio": "Hello world"
#}
#
#> {%
#    client.global.set("profileId", response.body.data.id);
#%}

### Get All Profiles (Admin)
GET {{host}}/profile/all?PageNumber=1&PageSize=10
Authorization: Bearer {{token}}

### Update Profile
PUT {{host}}/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "displayName": "Updated Name",
  "avatarUrl": "https://example.com/avatar-updated.png",
  "birthDate": "2000-01-01T00:00:00",
  "gender": 0,
  "bio": "Updated bio"
}

### Calculate BMI
POST {{host}}/bmi/calculate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "heightCm" : 180,
  "weightKg" : 65
}



### Planner
POST {{host}}/bmi/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "practiceLevel" : 1,
  "activityFactor" : 1.2
}